name: Build and Deploy Sphinx Documentation

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-docs:
    name: Build HTML and PDF Documentation
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      # Install dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y latexmk texlive texlive-latex-extra texlive-fonts-recommended texlive-lang-all
          python -m pip install --upgrade pip
          pip install sphinx

      # Build HTML documentation
      - name: Build HTML documentation
        working-directory: doc
        run: make html

      # Build PDF documentation
      - name: Build PDF documentation
        working-directory: doc
        run: make latexpdf

      # Move PDF to HTML directory for deployment
      - name: Copy PDF to HTML directory
        run: mv doc/build/latex/*.pdf doc/build/html/

      # Save PDF as an artifact from the HTML directory
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: sphinx-pdf
          path: doc/build/html/*.pdf

      # Debugging: Check contents of doc/build/html
      - name: List contents of doc/build/html
        run: ls -l doc/build/html

  deploy-html:
    name: Deploy HTML Documentation
    runs-on: ubuntu-latest
    needs: build-docs

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up gh-pages branch
      - name: Set up gh-pages branch
        run: |
          git fetch origin gh-pages || git checkout --orphan gh-pages
          git reset --hard

      # Debugging: Check if index.html exists in the publish directory
      - name: Check if index.html exists in publish directory
        run: |
          ls doc/build/html

      # Force add and commit files (if any changes exist)
      - name: Force commit changes
        run: |
          git add --all
          git commit -m "Deploy Sphinx documentation" || echo "No changes to commit"

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: doc/build/html

