name: Build and Deploy Sphinx Documentation

on:
  push:
    branches:
      - main  # Adjust the branch if necessary
  pull_request:

jobs:
  build-docs:
    name: Build HTML and PDF Documentation
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx

      # Build HTML documentation
      - name: Build HTML documentation
        working-directory: doc
        run: make html

      # Build PDF documentation
      - name: Build PDF documentation
        working-directory: doc
        run: make latexpdf

      # Save PDF as an artifact
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v3
        with:
          name: sphinx-pdf
          path: doc/build/latex/*.pdf

  deploy-html:
    name: Deploy HTML Documentation
    runs-on: ubuntu-latest
    needs: build-docs  # Ensure this job runs after building the docs

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Copy HTML build to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: doc/build/html

