name: Build and Deploy Sphinx Documentation

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-docs:
    name: Build HTML and PDF Documentation
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      # Install dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y latexmk texlive texlive-latex-extra texlive-fonts-recommended texlive-lang-all
          python -m pip install --upgrade pip
          pip install sphinx

      # Build HTML documentation
      - name: Build HTML documentation
        working-directory: doc
        run: |
          make html
          # Debugging: List contents of the build/html directory to ensure HTML files are created
          ls -l build/html

      # Build PDF documentation
      - name: Build PDF documentation
        working-directory: doc
        run: |
          make latexpdf
          # Debugging: List contents of the build/latex directory to check PDF generation
          ls -l build/latex

deploy-docs:
    name: Deploy Documentation
    runs-on: ubuntu-latest
    needs: build-docs

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: doc/build/html
          
      # Copy PDF file from latex build folder to the gh-pages branch
      - name: Copy PDF to GitHub Pages
        run: |
          mkdir -p doc/build/html/pdf
          cp doc/build/latex/*.pdf doc/build/html/pdf/
          # Commit and push the changes to gh-pages
          git add -A
          git commit -m "Deploy updated HTML and PDF documentation"
          git push

