name: Build and Deploy HTML Documentation

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-html:
    name: Build HTML Documentation
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      # Install dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y latexmk texlive texlive-latex-extra texlive-fonts-recommended texlive-lang-all
          python -m pip install --upgrade pip
          pip install sphinx

      # Build HTML documentation
      - name: Build HTML documentation
        working-directory: doc
        run: make html

  deploy-html:
    name: Deploy HTML Documentation to GitHub Pages
    runs-on: ubuntu-latest
    needs: build-html

    steps:
      # Checkout the repository again
      - name: Checkout repository
        uses: actions/checkout@v3

      # Deploy HTML to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: doc/build/html

