name: Build and Upload PDF Documentation

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-pdf:
    name: Build PDF Documentation
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      # Install dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y latexmk texlive texlive-latex-extra texlive-fonts-recommended texlive-lang-all
          python -m pip install --upgrade pip
          pip install sphinx

      # Build PDF documentation
      - name: Build PDF documentation
        working-directory: doc
        run: make latexpdf

  upload-pdf:
    name: Upload PDF Artifact
    runs-on: ubuntu-latest
    needs: build-pdf

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Upload PDF file as an artifact
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: sphinx-pdf
          path: doc/build/latex/*.pdf

