name: Deploy Sphinx PDF Documentation

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-pdf:
    name: Build and Deploy PDF Documentation
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Check out the repository
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      # Install dependencies
      - name: Install Sphinx and LaTeX dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y latexmk texlive texlive-latex-extra texlive-fonts-recommended texlive-lang-all
          python -m pip install --upgrade pip
          pip install sphinx

      # Build the PDF documentation
      - name: Build PDF documentation
        working-directory: doc
        run: make latexpdf

      # Deploy PDF to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: doc/build/latex
          destination_dir: pdf

